name: objd_crafting
description: This is an objD extension for a customizable crafting API
version: 0.1.0
homepage: https://www.stevertus.com/tools/crafting
author: Stevertus <stevertusyt@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  objd: ^0.2.2

