name: objd_crafting
description: This is an objD extension for a customizable crafting API
version: 0.2.0
homepage: https://www.stevertus.com
repository: https://github.com/Stevertus/objd_crafting
issue_tracker: https://github.com/Stevertus/objd_crafting/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  objd: ^0.4.1
dev_dependencies:
  pedantic: ^1.11.0
